// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLQuayThuoc.Data;

#nullable disable

namespace QLQuayThuoc.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.33")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("QLQuayThuoc.Models.BenhNhan", b =>
                {
                    b.Property<int>("MaBN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("GioiTinh")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("MaBHYT")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("MucHuongBHYT")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayHetHanBHYT")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("MaBN");

                    b.ToTable("BenhNhans");
                });

            modelBuilder.Entity("QLQuayThuoc.Models.ChiTietCapTheoLo", b =>
                {
                    b.Property<int>("MaPhieu")
                        .HasColumnType("int");

                    b.Property<int>("MaThuoc")
                        .HasColumnType("int");

                    b.Property<int>("MaLo")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongCap")
                        .HasColumnType("int");

                    b.HasKey("MaPhieu", "MaThuoc", "MaLo");

                    b.HasIndex("MaLo");

                    b.ToTable("ChiTietCapTheoLos");
                });

            modelBuilder.Entity("QLQuayThuoc.Models.ChiTietDonThuoc", b =>
                {
                    b.Property<int>("MaDonThuoc")
                        .HasColumnType("int");

                    b.Property<int>("MaThuoc")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LieuDung")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<int>("SoNgayDung")
                        .HasColumnType("int");

                    b.Property<string>("TanSuat")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("MaDonThuoc", "MaThuoc");

                    b.HasIndex("MaThuoc");

                    b.ToTable("ChiTietDonThuocs");
                });

            modelBuilder.Entity("QLQuayThuoc.Models.ChiTietPhieuXinCap", b =>
                {
                    b.Property<int>("MaPhieu")
                        .HasColumnType("int");

                    b.Property<int>("MaThuoc")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("SoLuongDuyet")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongYeuCau")
                        .HasColumnType("int");

                    b.HasKey("MaPhieu", "MaThuoc");

                    b.HasIndex("MaThuoc");

                    b.ToTable("ChiTietPhieuXinCaps");
                });

            modelBuilder.Entity("QLQuayThuoc.Models.ChiTietPhieuXuat", b =>
                {
                    b.Property<int>("MaPhieuXuat")
                        .HasColumnType("int");

                    b.Property<int>("MaLo")
                        .HasColumnType("int");

                    b.Property<decimal>("DonGiaBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaPhieuXuat", "MaLo");

                    b.HasIndex("MaLo");

                    b.ToTable("ChiTietPhieuXuats");
                });

            modelBuilder.Entity("QLQuayThuoc.Models.DonThuoc", b =>
                {
                    b.Property<int>("MaDonThuoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("BacSiId")
                        .HasColumnType("int");

                    b.Property<string>("ChanDoan")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("MaBN")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayKeDon")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("MaDonThuoc");

                    b.HasIndex("BacSiId");

                    b.HasIndex("MaBN");

                    b.ToTable("DonThuocs");
                });

            modelBuilder.Entity("QLQuayThuoc.Models.HoaDon", b =>
                {
                    b.Property<int>("MaHD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("MaGiaoDich")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("MaPhieuXuat")
                        .HasColumnType("int");

                    b.Property<string>("NoiDungChuyenKhoan")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PhuongThucThanhToan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("ThoiGianThanhToan")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("TienBHYTThanhToan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TienBenhNhanTra")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TienThuocDuocBHYT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongTienThuoc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TyLeBHYTApDung")
                        .HasColumnType("int");

                    b.HasKey("MaHD");

                    b.HasIndex("MaGiaoDich")
                        .IsUnique();

                    b.HasIndex("MaPhieuXuat")
                        .IsUnique();

                    b.ToTable("HoaDons");
                });

            modelBuilder.Entity("QLQuayThuoc.Models.Kho", b =>
                {
                    b.Property<int>("MaKho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("LoaiKho")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TenKho")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("MaKho");

                    b.ToTable("Khos");

                    b.HasData(
                        new
                        {
                            MaKho = 1,
                            LoaiKho = "KHO_TONG",
                            TenKho = "Kho tổng"
                        },
                        new
                        {
                            MaKho = 2,
                            LoaiKho = "KHO_QUAY",
                            TenKho = "Kho quầy"
                        });
                });

            modelBuilder.Entity("QLQuayThuoc.Models.LoThuoc", b =>
                {
                    b.Property<int>("MaLo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("MaThuoc")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayHetHan")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("NgaySanXuat")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SoLo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("MaLo");

                    b.HasIndex("MaThuoc", "SoLo")
                        .IsUnique();

                    b.ToTable("LoThuocs");
                });

            modelBuilder.Entity("QLQuayThuoc.Models.PhieuXinCapThuoc", b =>
                {
                    b.Property<int>("MaPhieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("GhiChuDuyet")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("KhoCapId")
                        .HasColumnType("int");

                    b.Property<int>("KhoNhanId")
                        .HasColumnType("int");

                    b.Property<string>("LyDo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("NgayDuyet")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("NguoiDuyetId")
                        .HasColumnType("int");

                    b.Property<int>("NguoiLapId")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("MaPhieu");

                    b.HasIndex("KhoCapId");

                    b.HasIndex("KhoNhanId");

                    b.HasIndex("NguoiDuyetId");

                    b.HasIndex("NguoiLapId");

                    b.ToTable("PhieuXinCapThuocs");
                });

            modelBuilder.Entity("QLQuayThuoc.Models.PhieuXuatThuoc", b =>
                {
                    b.Property<int>("MaPhieuXuat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DuocSiId")
                        .HasColumnType("int");

                    b.Property<int>("MaDonThuoc")
                        .HasColumnType("int");

                    b.Property<int>("MaKho")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayXuat")
                        .HasColumnType("datetime(6)");

                    b.HasKey("MaPhieuXuat");

                    b.HasIndex("DuocSiId");

                    b.HasIndex("MaDonThuoc")
                        .IsUnique();

                    b.HasIndex("MaKho");

                    b.ToTable("PhieuXuatThuocs");
                });

            modelBuilder.Entity("QLQuayThuoc.Models.Thuoc", b =>
                {
                    b.Property<int>("MaThuoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("DonGiaBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("DuocBHYTChiTra")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("HamLuong")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("HoatChat")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TenThuoc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("MaThuoc");

                    b.ToTable("Thuocs");
                });

            modelBuilder.Entity("QLQuayThuoc.Models.TonKho", b =>
                {
                    b.Property<int>("MaKho")
                        .HasColumnType("int");

                    b.Property<int>("MaLo")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("int");

                    b.HasKey("MaKho", "MaLo");

                    b.HasIndex("MaLo");

                    b.ToTable("TonKhos");
                });

            modelBuilder.Entity("QLQuayThuoc.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "admin@gmail.com",
                            FullName = "Quản trị viên",
                            IsActive = true,
                            PasswordHash = "AQAAAAEAAYagAAAAEAoi8S+gZ0EPMOKWIBoNTKwyLG/nnw896ohJOJu9e08MOxZeFhPyujJBQkB85AfiZw==",
                            PhoneNumber = "0000000000",
                            Role = "ADMIN"
                        });
                });

            modelBuilder.Entity("QLQuayThuoc.Models.ChiTietCapTheoLo", b =>
                {
                    b.HasOne("QLQuayThuoc.Models.LoThuoc", "LoThuoc")
                        .WithMany("ChiTietCapTheoLos")
                        .HasForeignKey("MaLo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLQuayThuoc.Models.ChiTietPhieuXinCap", "ChiTietPhieuXinCap")
                        .WithMany("ChiTietCapTheoLos")
                        .HasForeignKey("MaPhieu", "MaThuoc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChiTietPhieuXinCap");

                    b.Navigation("LoThuoc");
                });

            modelBuilder.Entity("QLQuayThuoc.Models.ChiTietDonThuoc", b =>
                {
                    b.HasOne("QLQuayThuoc.Models.DonThuoc", "DonThuoc")
                        .WithMany("ChiTietDonThuocs")
                        .HasForeignKey("MaDonThuoc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLQuayThuoc.Models.Thuoc", "Thuoc")
                        .WithMany("ChiTietDonThuocs")
                        .HasForeignKey("MaThuoc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DonThuoc");

                    b.Navigation("Thuoc");
                });

            modelBuilder.Entity("QLQuayThuoc.Models.ChiTietPhieuXinCap", b =>
                {
                    b.HasOne("QLQuayThuoc.Models.PhieuXinCapThuoc", "PhieuXinCapThuoc")
                        .WithMany("ChiTietPhieuXinCaps")
                        .HasForeignKey("MaPhieu")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLQuayThuoc.Models.Thuoc", "Thuoc")
                        .WithMany("ChiTietPhieuXinCaps")
                        .HasForeignKey("MaThuoc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PhieuXinCapThuoc");

                    b.Navigation("Thuoc");
                });

            modelBuilder.Entity("QLQuayThuoc.Models.ChiTietPhieuXuat", b =>
                {
                    b.HasOne("QLQuayThuoc.Models.LoThuoc", "LoThuoc")
                        .WithMany("ChiTietPhieuXuats")
                        .HasForeignKey("MaLo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLQuayThuoc.Models.PhieuXuatThuoc", "PhieuXuatThuoc")
                        .WithMany("ChiTietPhieuXuats")
                        .HasForeignKey("MaPhieuXuat")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LoThuoc");

                    b.Navigation("PhieuXuatThuoc");
                });

            modelBuilder.Entity("QLQuayThuoc.Models.DonThuoc", b =>
                {
                    b.HasOne("QLQuayThuoc.Models.User", "BacSi")
                        .WithMany("DonThuocs")
                        .HasForeignKey("BacSiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLQuayThuoc.Models.BenhNhan", "BenhNhan")
                        .WithMany("DonThuocs")
                        .HasForeignKey("MaBN")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BacSi");

                    b.Navigation("BenhNhan");
                });

            modelBuilder.Entity("QLQuayThuoc.Models.HoaDon", b =>
                {
                    b.HasOne("QLQuayThuoc.Models.PhieuXuatThuoc", "PhieuXuatThuoc")
                        .WithOne("HoaDon")
                        .HasForeignKey("QLQuayThuoc.Models.HoaDon", "MaPhieuXuat")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PhieuXuatThuoc");
                });

            modelBuilder.Entity("QLQuayThuoc.Models.LoThuoc", b =>
                {
                    b.HasOne("QLQuayThuoc.Models.Thuoc", "Thuoc")
                        .WithMany("LoThuocs")
                        .HasForeignKey("MaThuoc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Thuoc");
                });

            modelBuilder.Entity("QLQuayThuoc.Models.PhieuXinCapThuoc", b =>
                {
                    b.HasOne("QLQuayThuoc.Models.Kho", "KhoCap")
                        .WithMany("PhieuCapDi")
                        .HasForeignKey("KhoCapId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLQuayThuoc.Models.Kho", "KhoNhan")
                        .WithMany("PhieuNhanVe")
                        .HasForeignKey("KhoNhanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLQuayThuoc.Models.User", "NguoiDuyet")
                        .WithMany("PhieuDaDuyet")
                        .HasForeignKey("NguoiDuyetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QLQuayThuoc.Models.User", "NguoiLap")
                        .WithMany("PhieuDaLap")
                        .HasForeignKey("NguoiLapId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KhoCap");

                    b.Navigation("KhoNhan");

                    b.Navigation("NguoiDuyet");

                    b.Navigation("NguoiLap");
                });

            modelBuilder.Entity("QLQuayThuoc.Models.PhieuXuatThuoc", b =>
                {
                    b.HasOne("QLQuayThuoc.Models.User", "DuocSi")
                        .WithMany("PhieuXuatThuocs")
                        .HasForeignKey("DuocSiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLQuayThuoc.Models.DonThuoc", "DonThuoc")
                        .WithOne("PhieuXuatThuoc")
                        .HasForeignKey("QLQuayThuoc.Models.PhieuXuatThuoc", "MaDonThuoc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLQuayThuoc.Models.Kho", "Kho")
                        .WithMany("PhieuXuatThuocs")
                        .HasForeignKey("MaKho")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DonThuoc");

                    b.Navigation("DuocSi");

                    b.Navigation("Kho");
                });

            modelBuilder.Entity("QLQuayThuoc.Models.TonKho", b =>
                {
                    b.HasOne("QLQuayThuoc.Models.Kho", "Kho")
                        .WithMany("TonKhos")
                        .HasForeignKey("MaKho")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLQuayThuoc.Models.LoThuoc", "LoThuoc")
                        .WithMany("TonKhos")
                        .HasForeignKey("MaLo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kho");

                    b.Navigation("LoThuoc");
                });

            modelBuilder.Entity("QLQuayThuoc.Models.BenhNhan", b =>
                {
                    b.Navigation("DonThuocs");
                });

            modelBuilder.Entity("QLQuayThuoc.Models.ChiTietPhieuXinCap", b =>
                {
                    b.Navigation("ChiTietCapTheoLos");
                });

            modelBuilder.Entity("QLQuayThuoc.Models.DonThuoc", b =>
                {
                    b.Navigation("ChiTietDonThuocs");

                    b.Navigation("PhieuXuatThuoc");
                });

            modelBuilder.Entity("QLQuayThuoc.Models.Kho", b =>
                {
                    b.Navigation("PhieuCapDi");

                    b.Navigation("PhieuNhanVe");

                    b.Navigation("PhieuXuatThuocs");

                    b.Navigation("TonKhos");
                });

            modelBuilder.Entity("QLQuayThuoc.Models.LoThuoc", b =>
                {
                    b.Navigation("ChiTietCapTheoLos");

                    b.Navigation("ChiTietPhieuXuats");

                    b.Navigation("TonKhos");
                });

            modelBuilder.Entity("QLQuayThuoc.Models.PhieuXinCapThuoc", b =>
                {
                    b.Navigation("ChiTietPhieuXinCaps");
                });

            modelBuilder.Entity("QLQuayThuoc.Models.PhieuXuatThuoc", b =>
                {
                    b.Navigation("ChiTietPhieuXuats");

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("QLQuayThuoc.Models.Thuoc", b =>
                {
                    b.Navigation("ChiTietDonThuocs");

                    b.Navigation("ChiTietPhieuXinCaps");

                    b.Navigation("LoThuocs");
                });

            modelBuilder.Entity("QLQuayThuoc.Models.User", b =>
                {
                    b.Navigation("DonThuocs");

                    b.Navigation("PhieuDaDuyet");

                    b.Navigation("PhieuDaLap");

                    b.Navigation("PhieuXuatThuocs");
                });
#pragma warning restore 612, 618
        }
    }
}
